feat(oauth): add getToken() and setToken() methods
goabstract/abstract-sdk pull request #290
Opened 2020-07-10 13:34 UTC by berezovskycom

This PR is the 3rd part of adding OAuth2.0 into Abstract SDK.
[Link to OAUTH2.0 RFC](https://goabstract.atlassian.net/wiki/spaces/ENG/pages/341705615/OAuth+2.0)
[Link to OAuth interface for SDK](https://goabstract.atlassian.net/wiki/spaces/ENG/pages/447643698/RFC+OAuth+interface+for+JavaScript+SDK#Architecture-Summary)

Adds add `getToken()` for making a `POST` request to `auth/tokens` with `authorizationCode`.
And `setToken()` for storing returned `accessToken` in client.

Example:

```
let abstract = new Abstract.Client({
  clientId,
  clientSecret,
  redirectUri,
});

async function oAuth(code) {
  return await abstract.oauth
    .getToken({
      authorizationCode: code
    })
    .then(token => {
      abstract = abstract.oauth.setToken(token);

      return abstract;
    })
    .catch(error => console.log(error));
}

const authorizedAbstract = oAuth("authentication_code");

authorizedAbstract.then(() => {
  // use sdk as usual
});
```

Things to consider:
`client.oauth.setToken()` returns `new Client({})` with the same `options + accessToken`.
Is it really possible to change options for Client and all other endpoints without returning a new class?
I've tried a few ways, but the only `options` get changed are in `oauth` endpoint. Any thoughts?

2020-07-10 22:41 UTC, amccloud commented on src/endpoints/Oauth.js
> +    return this.configureRequest<Promise<TokenResponseData>>("info", {
```suggestion
    return this.configureRequest<Promise<TokenResponseData>>("getToken", {
```

2020-07-10 22:41 UTC, amccloud commented on src/endpoints/Oauth.js
> +    });
@berezovskycom I wish I noticed all your code at once. I would have suggested keeping https://github.com/goabstract/abstract-sdk/pull/289 what you had originally vs making it match the spec

At the time of my suggestion I hadn't realized you created this oauth endpoint for `getToken` which does end up using `this.apiRequest` from `Endpoint`. I think you made the right choice and It would also be a consistent developer experience to have `getToken`, `setToken`, and `getAuthroizeUrl` together - like what you originally had 🙃

Endpoint options will not necessarily always match the client options so copying endpoint options to create a new client may not be not ideal

@tommoor now that we're here not sure which direction you want to go. Compared to spec, `setToken` here  is returning a new instance of Client, which I think could be preferred to mutating the original client options?

The api call above requiring this to be an endpoint to begin with may also be simple enough for calling fetch from Client?

2020-07-10 22:41 UTC, amccloud commented on src/endpoints/Oauth.js
> +            customHostname: "https://auth.goabstract.com"
@tommoor still use goabstract.com or do you know if we can switch to abstract.com?

2020-07-10 22:41 UTC, amccloud commented on src/endpoints/Oauth.js
> +    let redirectUri = descriptor.redirectUri || this.options.redirectUri;
Can you also update this to an input type like in #289?

2020-07-10 22:41 UTC, amccloud commented on src/errors.js
> +
Not used?

2020-07-10 22:41 UTC, amccloud commented on src/endpoints/Endpoint.js
> +    // fetchOptions.body = fetchOptions.body && JSON.stringify(fetchOptions.body);
👀

2020-07-13 09:29 UTC, berezovskycom commented on src/endpoints/Oauth.js
> +    });
Hi Andrew!
Thanks for reviewing the code.
I think it would be better if to keep both requests at once, so I will add the `getAuthorizeUrl` here :)

+1 for mutating the original client options, I'm not really sure what is the best way to accomplish that.
If you do something like `this.options = { ...this.options, accessToken }`, `this.options` will be changed only in OAuth endpoint. Do you have any ideas?

2020-07-13 19:07 UTC, tommoor commented
Looks like a bunch of unrelated work from master is showing up in the PR

2020-07-15 03:14 UTC, amccloud reviewed
Thanks for consolidating the PRs 🙏 

I think once you get the commits in this PR cleaned up you should be all set for review

2020-07-15 03:14 UTC, amccloud commented on src/endpoints/OAuth.js
> +    // $FlowFixMe
We typically try to avoid type suppressions unless it is absolutely necessary. If flow is warning here it's likely you have an unaccounted for state here

You can guard appending things to body by either providing a default 

```js
body.append("redirect_uri", window.location.href);
```

or returning early before you pass empty values to the body:

```js
if (!clientId || !clientSecret) {
  throw new Error('OAuthOnAuthorizeToken required');
}
```

2020-07-15 03:14 UTC, amccloud commented on src/types.js
> +export type OAuthOnAuthorizeToken = {
Since this is the input for getToken

```suggestion
export type OAuthTokenInput = {
```

`OAuthOnAuthorizeToken` seems like what `authorizationCode` is and that's only part of the input

2020-07-15 21:51 UTC, berezovskycom commented on src/endpoints/Endpoint.js
> +    // fetchOptions.body = fetchOptions.body && JSON.stringify(fetchOptions.body);
Yup, saw that. OAuth post request requires `"application/x-www-form-urlencoded"`, not JSON. Shall we add optional param to check if `JSON.stringify()` will not get used?

2020-07-15 21:52 UTC, amccloud commented on src/endpoints/Endpoint.js
> +    // fetchOptions.body = fetchOptions.body && JSON.stringify(fetchOptions.body);
Extra option or introspecting the headers to see if we're sending content-type: application/x-www-form-urlencoded

2020-07-15 22:09 UTC, berezovskycom commented on src/endpoints/Endpoint.js
> +    // fetchOptions.body = fetchOptions.body && JSON.stringify(fetchOptions.body);
Great idea!

2020-07-17 18:01 UTC, tommoor commented on src/endpoints/Oauth.js
> +            customHostname: "https://auth.goabstract.com"
I don't know, best keep it safe.

2020-07-17 18:01 UTC, tommoor commented
Please move out of draft and re-ping when you're ready for final review.

2020-07-20 17:07 UTC, tommoor commented on src/endpoints/Oauth.js
> +    });
In agreement that the existing client should be mutated and returned – `Endpoint` has a `this.client` available so you should be able to mutate that and return it.

2020-07-20 22:54 UTC, berezovskycom commented on src/endpoints/Oauth.js
> +    });
Hi @tommoor @amccloud! Thanks for comments - added new commit where `client.options` gets mutated. Works as expected. Converting pr from draft to a pr and waiting for comments & approval :)

2020-07-20 23:11 UTC, amccloud reviewed
Looks great 👍 

Before merging can we start to stub out documentation for this feature? Would be nice to cover what this PR includes

2020-07-21 22:37 UTC, tommoor requested changes
Almost there, I hope to get chance to spin up a sample app to really test before final approval.

2020-07-21 22:37 UTC, tommoor commented on abstract-sdk.d.ts
> +  clientSecret?: string | Promise<string>,
```suggestion
  clientSecret?: string,
```

2020-07-21 22:37 UTC, tommoor commented on abstract-sdk.d.ts
> +  redirectUri?: string | Promise<string>,
```suggestion
  redirectUri?: string,
```

We're not supporting Promises here

2020-07-21 22:37 UTC, tommoor commented on src/Client.js
> +    this._analyticsCallback = this.options.analyticsCallback;
I think we should go ahead and just change `Endpoint` to only accept one argument, `this` – we can read `this.options` in the constructor and avoid passing it in essentially twice here.

2020-07-21 22:37 UTC, tommoor commented on src/endpoints/Endpoint.js
> +
```suggestion
    if (
      !fetchOptions.headers || fetchOptions.headers["Content-Type"] !==
        "application/x-www-form-urlencoded"
    ) {
      fetchOptions.body =
        fetchOptions.body && JSON.stringify(fetchOptions.body);
    }

```

Suggesting this change to keep the same functionality if `headers` is present, but `Content-Type` isn't.

2020-07-21 22:37 UTC, tommoor commented on src/endpoints/OAuth.js
> +        "Client credentials are missing. Please doublecheck clientId, redirectUri and state"
```suggestion
        "Client credentials are missing. Please double check clientId, redirectUri and state"
```

2020-07-21 22:37 UTC, tommoor commented on src/endpoints/OAuth.js
> +    if (!clientId || !state || !redirectUri) {
Is `state` strictly required?

2020-07-21 22:37 UTC, tommoor commented on src/endpoints/OAuth.js
> +    )}&response_type=code&scope=all&state=${state}`;
Can we allow `input.scope` here to future proof and just set it to "all" as the default?

2020-07-21 22:37 UTC, tommoor commented on src/types.js
> +  id: string,
What is this `id`?

2020-07-21 22:37 UTC, tommoor commented on src/Client.js
> +    return this.options;
Did you have a reason for returning options here in mind? Might be confusing, could be better to return `this` to allow for chaining or nothing at all…

2020-07-22 17:46 UTC, berezovskycom commented on src/endpoints/OAuth.js
> +    if (!clientId || !state || !redirectUri) {
Nope. Will fix that 👍

2020-07-22 17:51 UTC, berezovskycom commented on src/endpoints/OAuth.js
> +    )}&response_type=code&scope=all&state=${state}`;
Good!

2020-07-22 17:52 UTC, berezovskycom commented on src/types.js
> +  id: string,
According to back end, it's not used anywhere right now and not much needed for client. Looks like an id in database.

2020-07-22 17:52 UTC, berezovskycom commented on src/Client.js
> +    return this.options;
Yes, 100% agree. Returning nothing lgtm. Will fix that in new commit.

2020-07-22 18:16 UTC, berezovskycom commented on src/Client.js
> +    this._analyticsCallback = this.options.analyticsCallback;
Done! I left Endpoint options param as optional, because tests were behaving weird.

2020-07-22 18:16 UTC, berezovskycom commented on src/endpoints/OAuth.js
> +    if (!clientId || !state || !redirectUri) {
Done!

2020-07-22 18:17 UTC, berezovskycom commented on src/endpoints/OAuth.js
> +    )}&response_type=code&scope=all&state=${state}`;
Pushed.

2020-07-22 18:17 UTC, berezovskycom commented on src/Client.js
> +    return this.options;
Fixed and edited tests.

2020-07-22 18:18 UTC, berezovskycom commented on src/endpoints/Endpoint.js
> +    this.options = options ? options : this.client.options;
Not really sure if that's the best idea, but test are feeling fine.

2020-07-22 18:20 UTC, berezovskycom commented
Me & @Geek-1001 are preparing docs for OAuth, we will let you know when it gets finished!

2020-07-23 19:49 UTC, tommoor commented on src/endpoints/OAuth.js
> +    const scope = "all";
```suggestion
    const scope = input.scope || "all";
```

Kinda meant this

2020-07-23 19:50 UTC, tommoor approved these changes

2025-10-12 13:47 UTC, closed without merging